# Generated by Django 4.2 on 2023-04-21 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vsetaq', '0007_goals_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_income', models.DecimalField(decimal_places=2, max_digits=50)),
                ('category', models.CharField(default='', max_length=100)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
